# Generated by Django 3.0.5 on 2020-06-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
